-- 가계부 프로젝트 DB 스키마
-- Supabase SQL Editor에서 실행하세요.

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date text not null,
  amount integer not null,
  description text not null,
  constraint expenses_amount_positive check (amount > 0),
  constraint expenses_description_not_empty check (char_length(trim(description)) > 0)
);

comment on table public.expenses is '가계부 지출 내역';
comment on column public.expenses.date is '지출 날짜 (YYYY-MM-DD)';
comment on column public.expenses.amount is '지출 금액 (원, 정수)';
comment on column public.expenses.description is '지출 내용';

create index if not exists expenses_created_at_idx
  on public.expenses (created_at desc);

alter table public.expenses enable row level security;

drop policy if exists "Allow public select on expenses" on public.expenses;
drop policy if exists "Allow public insert on expenses" on public.expenses;
drop policy if exists "Allow public delete on expenses" on public.expenses;
drop policy if exists "Allow public access to expenses" on public.expenses;

-- 현재 앱은 로그인 없이 브라우저에서 직접 접근하므로 anon 권한을 허용합니다.
-- 인증을 붙인 뒤에는 user_id 기준으로 정책을 바꾸는 것을 권장합니다.
create policy "Allow public select on expenses"
  on public.expenses
  for select
  to anon, authenticated
  using (true);

create policy "Allow public insert on expenses"
  on public.expenses
  for insert
  to anon, authenticated
  with check (true);

create policy "Allow public delete on expenses"
  on public.expenses
  for delete
  to anon, authenticated
  using (true);

grant usage on schema public to anon, authenticated;
grant select, insert, delete on table public.expenses to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
